// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transfer.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TransferScheme _$TransferSchemeFromJson(
  Map<String, dynamic> json,
) => TransferScheme(
  refKey: json['Ref_Key'] as String,
  dataVersion: json['DataVersion'] as String?,
  deletionMark: json['DeletionMark'] as bool?,
  number: json['Number'] as String,
  date: DateTime.parse(json['Date'] as String),
  posted: json['Posted'] as bool?,
  carKey: json['Автомобиль_Key'] as String?,
  authorKey: json['Автор_Key'] as String?,
  deliveryAddress: json['АдресДоставки'] as String?,
  deliveryAddressValue: json['АдресДоставкиЗначение'] as String?,
  deliveryAddressFieldsValues: json['АдресДоставкиЗначенияПолей'] as String?,
  carrierBankAccountKey: json['БанковскийСчетПеревозчика_Key'] as String?,
  weight: (json['Вес'] as num?)?.toDouble(),
  operationType: json['ВидОперации'] as String?,
  priceTypesKey: json['ВидыЦен_Key'] as String?,
  driverKey: json['Водитель_Key'] as String?,
  isReturn: json['Возврат'] as bool?,
  senderKey: json['Грузоотправитель_Key'] as String?,
  receiverKey: json['Грузополучатель_Key'] as String?,
  powerOfAttorneyIssued: json['ДоверенностьВыдана'] as String?,
  powerOfAttorneyDate: json['ДоверенностьДата'] == null
      ? null
      : DateTime.parse(json['ДоверенностьДата'] as String),
  powerOfAttorneyPersonKey: json['ДоверенностьЛицо_Key'] as String?,
  powerOfAttorneyNumber: json['ДоверенностьНомер'] as String?,
  baseDocument: json['ДокументОснование'] as String?,
  baseDocumentType: json['ДокументОснование_Type'] as String?,
  shipmentDocumentKey: json['ДокументОтгрузки_Key'] as String?,
  receiptDocumentKey: json['ДокументПоступления_Key'] as String?,
  additionalDeliveryInfo: json['ДополнительнаяИнформацияПоДоставке'] as String?,
  hasDiscounts: json['ЕстьСкидки'] as bool?,
  order: json['Заказ'] as String?,
  transferOrderKey: json['ЗаказНаПеремещение_Key'] as String?,
  customerOrderKey: json['ЗаказПокупателя_Key'] as String?,
  closedAt: json['Закрыт'] == null
      ? null
      : DateTime.parse(json['Закрыт'] as String),
  total: (json['Итого'] as num?)?.toDouble(),
  traceabilityOpCodeKey: json['КодОперацииПрослеживаемости_Key'] as String?,
  comment: json['Комментарий'] as String?,
  lineOfBusinessKey: json['НаправлениеДеятельности_Key'] as String?,
  volume: (json['Объем'] as num?)?.toDouble(),
  organizationKey: json['Организация_Key'] as String?,
  isOriginal: json['Оригинал'] as bool?,
  printBase: json['ОснованиеПечати'] as String?,
  printBaseRef: json['ОснованиеПечатиСсылка'] as String?,
  printBaseRefType: json['ОснованиеПечатиСсылка_Type'] as String?,
  responsibleKey: json['Ответственный_Key'] as String?,
  openedAt: json['Открыт'] == null
      ? null
      : DateTime.parse(json['Открыт'] as String),
  isSent: json['Отправлен'] as bool?,
  carrierKey: json['Перевозчик_Key'] as String?,
  chiefAccountantSignatureKey: json['ПодписьГлавногоБухгалтера_Key'] as String?,
  senderStorekeeperSignatureKey:
      json['ПодписьКладовщикаОтправил_Key'] as String?,
  receiverStorekeeperSignatureKey:
      json['ПодписьКладовщикаПолучил_Key'] as String?,
  controllerSignatureKey: json['ПодписьКонтролера_Key'] as String?,
  directorSignatureKey: json['ПодписьРуководителя_Key'] as String?,
  customerOrderPosition: json['ПоложениеЗаказаПокупателя'] as String?,
  taxSettingsPosition: json['ПоложениеНастроекНалоговогоУчета'] as String?,
  projectPosition: json['ПоложениеПроекта'] as String?,
  senderCellPosition: json['ПоложениеЯчейкиОтправителя'] as String?,
  receiverCellPosition: json['ПоложениеЯчейкиПолучателя'] as String?,
  isAccepted: json['Принят'] as bool,
  trailerKey: json['Прицеп_Key'] as String?,
  isChecked: json['Проверено'] as bool?,
  projectKey: json['Проект_Key'] as String?,
  orderStatusKey: json['СостояниеЗаказа_Key'] as String?,
  employeeKey: json['Сотрудник_Key'] as String?,
  deliveryDeadline: json['СрокДоставки'] == null
      ? null
      : DateTime.parse(json['СрокДоставки'] as String),
  senderUnitKey: json['СтруктурнаяЕдиница_Key'] as String?,
  receiverUnitKey: json['СтруктурнаяЕдиницаПолучатель_Key'] as String?,
  documentAmount: (json['СуммаДокумента'] as num?)?.toDouble(),
  costAccountKey: json['СчетЗатрат_Key'] as String?,
  goodsTransferredInWorks: json['ТоварыПередаютсяВСоставеРабот'] as bool?,
  deleteChiefAccountantKey: json['УдалитьГлавныйБухгалтер_Key'] as String?,
  deleteReleasedByKey: json['УдалитьОтпустил_Key'] as String?,
  deleteReleasedByPositionKey: json['УдалитьОтпустилДолжность_Key'] as String?,
  deleteDirectorKey: json['УдалитьРуководитель_Key'] as String?,
  deleteDirectorPositionKey:
      json['УдалитьРуководительДолжность_Key'] as String?,
  includeInTaxAccounting: json['УчитыватьВНУ'] as bool?,
  businessOperationKey: json['ХозяйственнаяОперация_Key'] as String?,
  cellKey: json['Ячейка_Key'] as String?,
  receiverCellKey: json['ЯчейкаПолучатель_Key'] as String?,
  assemblyWarehouseKey: json['СкладСборки_Key'] as String?,
  priceTypeKey: json['ВидЦен_Key'] as String?,
  isLocked: json['Заблокировано'] as bool?,
  inventory: (json['Запасы'] as List<dynamic>)
      .map((e) => InventoryItem.fromJson(e as Map<String, dynamic>))
      .toList(),
  specialEquipment: json['Спецоснастка'] as List<dynamic>?,
  inventoryAndSupplies:
      json['ИнвентарьИХозяйственныеПринадлежности'] as List<dynamic>?,
  nomenclatureSeries: json['СерииНоменклатуры'] as List<dynamic>?,
  additionalAttributes: json['ДополнительныеРеквизиты'] as List<dynamic>?,
  traceabilityInfo: json['СведенияПрослеживаемости'] as List<dynamic>?,
  productGroups: json['ГруппыТоваров'] as List<dynamic>?,
  packages: json['Упоковки'] as List<dynamic>?,
);

Map<String, dynamic> _$TransferSchemeToJson(TransferScheme instance) =>
    <String, dynamic>{
      'Ref_Key': instance.refKey,
      'DataVersion': ?instance.dataVersion,
      'DeletionMark': ?instance.deletionMark,
      'Number': instance.number,
      'Date': instance.date.toIso8601String(),
      'Posted': ?instance.posted,
      'Автомобиль_Key': ?instance.carKey,
      'Автор_Key': ?instance.authorKey,
      'АдресДоставки': ?instance.deliveryAddress,
      'АдресДоставкиЗначение': ?instance.deliveryAddressValue,
      'АдресДоставкиЗначенияПолей': ?instance.deliveryAddressFieldsValues,
      'БанковскийСчетПеревозчика_Key': ?instance.carrierBankAccountKey,
      'Вес': ?instance.weight,
      'ВидОперации': ?instance.operationType,
      'ВидыЦен_Key': ?instance.priceTypesKey,
      'Водитель_Key': ?instance.driverKey,
      'Возврат': ?instance.isReturn,
      'Грузоотправитель_Key': ?instance.senderKey,
      'Грузополучатель_Key': ?instance.receiverKey,
      'ДоверенностьВыдана': ?instance.powerOfAttorneyIssued,
      'ДоверенностьДата': ?instance.powerOfAttorneyDate?.toIso8601String(),
      'ДоверенностьЛицо_Key': ?instance.powerOfAttorneyPersonKey,
      'ДоверенностьНомер': ?instance.powerOfAttorneyNumber,
      'ДокументОснование': ?instance.baseDocument,
      'ДокументОснование_Type': ?instance.baseDocumentType,
      'ДокументОтгрузки_Key': ?instance.shipmentDocumentKey,
      'ДокументПоступления_Key': ?instance.receiptDocumentKey,
      'ДополнительнаяИнформацияПоДоставке': ?instance.additionalDeliveryInfo,
      'ЕстьСкидки': ?instance.hasDiscounts,
      'Заказ': ?instance.order,
      'ЗаказНаПеремещение_Key': ?instance.transferOrderKey,
      'ЗаказПокупателя_Key': ?instance.customerOrderKey,
      'Закрыт': ?instance.closedAt?.toIso8601String(),
      'Итого': ?instance.total,
      'КодОперацииПрослеживаемости_Key': ?instance.traceabilityOpCodeKey,
      'Комментарий': ?instance.comment,
      'НаправлениеДеятельности_Key': ?instance.lineOfBusinessKey,
      'Объем': ?instance.volume,
      'Организация_Key': ?instance.organizationKey,
      'Оригинал': ?instance.isOriginal,
      'ОснованиеПечати': ?instance.printBase,
      'ОснованиеПечатиСсылка': ?instance.printBaseRef,
      'ОснованиеПечатиСсылка_Type': ?instance.printBaseRefType,
      'Ответственный_Key': ?instance.responsibleKey,
      'Открыт': ?instance.openedAt?.toIso8601String(),
      'Отправлен': ?instance.isSent,
      'Перевозчик_Key': ?instance.carrierKey,
      'ПодписьГлавногоБухгалтера_Key': ?instance.chiefAccountantSignatureKey,
      'ПодписьКладовщикаОтправил_Key': ?instance.senderStorekeeperSignatureKey,
      'ПодписьКладовщикаПолучил_Key': ?instance.receiverStorekeeperSignatureKey,
      'ПодписьКонтролера_Key': ?instance.controllerSignatureKey,
      'ПодписьРуководителя_Key': ?instance.directorSignatureKey,
      'ПоложениеЗаказаПокупателя': ?instance.customerOrderPosition,
      'ПоложениеНастроекНалоговогоУчета': ?instance.taxSettingsPosition,
      'ПоложениеПроекта': ?instance.projectPosition,
      'ПоложениеЯчейкиОтправителя': ?instance.senderCellPosition,
      'ПоложениеЯчейкиПолучателя': ?instance.receiverCellPosition,
      'Принят': instance.isAccepted,
      'Прицеп_Key': ?instance.trailerKey,
      'Проверено': ?instance.isChecked,
      'Проект_Key': ?instance.projectKey,
      'СостояниеЗаказа_Key': ?instance.orderStatusKey,
      'Сотрудник_Key': ?instance.employeeKey,
      'СрокДоставки': ?instance.deliveryDeadline?.toIso8601String(),
      'СтруктурнаяЕдиница_Key': ?instance.senderUnitKey,
      'СтруктурнаяЕдиницаПолучатель_Key': ?instance.receiverUnitKey,
      'СуммаДокумента': ?instance.documentAmount,
      'СчетЗатрат_Key': ?instance.costAccountKey,
      'ТоварыПередаютсяВСоставеРабот': ?instance.goodsTransferredInWorks,
      'УдалитьГлавныйБухгалтер_Key': ?instance.deleteChiefAccountantKey,
      'УдалитьОтпустил_Key': ?instance.deleteReleasedByKey,
      'УдалитьОтпустилДолжность_Key': ?instance.deleteReleasedByPositionKey,
      'УдалитьРуководитель_Key': ?instance.deleteDirectorKey,
      'УдалитьРуководительДолжность_Key': ?instance.deleteDirectorPositionKey,
      'УчитыватьВНУ': ?instance.includeInTaxAccounting,
      'ХозяйственнаяОперация_Key': ?instance.businessOperationKey,
      'Ячейка_Key': ?instance.cellKey,
      'ЯчейкаПолучатель_Key': ?instance.receiverCellKey,
      'СкладСборки_Key': ?instance.assemblyWarehouseKey,
      'ВидЦен_Key': ?instance.priceTypeKey,
      'Заблокировано': ?instance.isLocked,
      'Запасы': instance.inventory,
      'Спецоснастка': ?instance.specialEquipment,
      'ИнвентарьИХозяйственныеПринадлежности': ?instance.inventoryAndSupplies,
      'СерииНоменклатуры': ?instance.nomenclatureSeries,
      'ДополнительныеРеквизиты': ?instance.additionalAttributes,
      'СведенияПрослеживаемости': ?instance.traceabilityInfo,
      'ГруппыТоваров': ?instance.productGroups,
      'Упоковки': ?instance.packages,
      'Заказ_Type': instance.orderType,
    };

InventoryItem _$InventoryItemFromJson(Map<String, dynamic> json) =>
    InventoryItem(
      refKey: json['Ref_Key'] as String,
      lineNumber: json['LineNumber'] as String,
      nomenclatureKey: json['Номенклатура_Key'] as String,
      characteristicKey: json['Характеристика_Key'] as String?,
      batchKey: json['Партия_Key'] as String?,
      nomenclatureSeries: json['СерииНоменклатуры'] as String?,
      quantity: (json['Количество'] as num).toDouble(),
      reserve: (json['Резерв'] as num?)?.toDouble(),
      unitOfMeasureKey: json['ЕдиницаИзмерения'] as String?,
      unitOfMeasureType: json['ЕдиницаИзмерения_Type'] as String?,
      customerOrderKey: json['ЗаказПокупателя_Key'] as String?,
      cost: (json['Себестоимость'] as num?)?.toDouble(),
      connectionKey: json['КлючСвязи'] as String?,
      countryOfOriginKey: json['СтранаПроисхождения_Key'] as String?,
      gtdNumberKey: json['НомерГТД_Key'] as String?,
      projectKey: json['Проект_Key'] as String?,
      rowIdentifier: json['ИдентификаторСтроки'] as String?,
      isTraceableItem: json['ПрослеживаемыйТовар'] as bool?,
      isTraceableKit: json['ПрослеживаемыйКомплект'] as bool?,
      price: (json['Цена'] as num).toDouble(),
      includeInTaxAccounting: json['УчитыватьВНУ'] as bool?,
      cellKey: json['Ячейка_Key'] as String?,
      receiverCellKey: json['ЯчейкаПолучатель_Key'] as String?,
      weight: (json['Вес'] as num?)?.toDouble(),
      volume: (json['Объем'] as num?)?.toDouble(),
      sum: (json['Сумма'] as num).toDouble(),
      groupKey: json['Группа_Key'] as String?,
      ordered: (json['Заказано'] as num?)?.toDouble(),
      balance: (json['Остаток'] as num?)?.toDouble(),
      discount: json['Скидка'] as String?,
    );

Map<String, dynamic> _$InventoryItemToJson(InventoryItem instance) =>
    <String, dynamic>{
      'Ref_Key': instance.refKey,
      'LineNumber': instance.lineNumber,
      'Номенклатура_Key': instance.nomenclatureKey,
      'Характеристика_Key': ?instance.characteristicKey,
      'Партия_Key': ?instance.batchKey,
      'СерииНоменклатуры': ?instance.nomenclatureSeries,
      'Количество': instance.quantity,
      'Резерв': ?instance.reserve,
      'ЕдиницаИзмерения': ?instance.unitOfMeasureKey,
      'ЕдиницаИзмерения_Type': ?instance.unitOfMeasureType,
      'ЗаказПокупателя_Key': ?instance.customerOrderKey,
      'Себестоимость': ?instance.cost,
      'КлючСвязи': ?instance.connectionKey,
      'СтранаПроисхождения_Key': ?instance.countryOfOriginKey,
      'НомерГТД_Key': ?instance.gtdNumberKey,
      'Проект_Key': ?instance.projectKey,
      'ИдентификаторСтроки': ?instance.rowIdentifier,
      'ПрослеживаемыйТовар': ?instance.isTraceableItem,
      'ПрослеживаемыйКомплект': ?instance.isTraceableKit,
      'Цена': instance.price,
      'УчитыватьВНУ': ?instance.includeInTaxAccounting,
      'Ячейка_Key': ?instance.cellKey,
      'ЯчейкаПолучатель_Key': ?instance.receiverCellKey,
      'Вес': ?instance.weight,
      'Объем': ?instance.volume,
      'Сумма': instance.sum,
      'Группа_Key': ?instance.groupKey,
      'Заказано': ?instance.ordered,
      'Остаток': ?instance.balance,
      'Скидка': ?instance.discount,
    };

TransferListScheme _$TransferListSchemeFromJson(Map<String, dynamic> json) =>
    TransferListScheme(
      value: (json['value'] as List<dynamic>)
          .map((e) => TransferScheme.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$TransferListSchemeToJson(TransferListScheme instance) =>
    <String, dynamic>{'value': instance.value};

TransferUpdateScheme _$TransferUpdateSchemeFromJson(
  Map<String, dynamic> json,
) => TransferUpdateScheme(
  transferDate: DateTime.parse(json['ДатаПриемки'] as String),
  isAccepted: json['Принят'] as bool,
);

Map<String, dynamic> _$TransferUpdateSchemeToJson(
  TransferUpdateScheme instance,
) => <String, dynamic>{
  'ДатаПриемки': instance.transferDate.toIso8601String(),
  'Принят': instance.isAccepted,
};
