### Получение явок сотрудников
GET {{$dotenv API}}/InformationRegister_ЯвкиСотрудников
    ?$format=json
    &$top=1
    &$orderby=ДатаПересечения desc
    &$filter=Сотрудник_Key eq guid'b882bb25-aade-11ee-a976-f4b520322e15'
    # &$select=Момент,ДатаПересечения
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Accept: application/json

    ## Ответ
    #   "Сотрудник_Key": "b882bb25-aade-11ee-a976-f4b520322e15",
    #   "Терминал_Key": "787abe65-4db7-11f0-be1f-00155d00f705",
    #   "Выход": "Чыгуу (Выход)",
    #   "Момент": 0,
    #   "Минута": "1",
    #   "ДатаПересечения": "2026-03-13T20:01:00",
    #   "Статус": "",
    #   "ФИО": "Жороева Акылай",
    #   "Обновил_Key": "00000000-0000-0000-0000-000000000000",
    #   "Место_Key": "021f4fa9-3377-11ed-91a8-a068f8f3337c",
    #   "НомерПропуска": "",


### Создание явки Вход

POST {{$dotenv API}}/InformationRegister_ЯвкиСотрудников
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Accept: application/json

{
    "Сотрудник_Key": "b882bb25-aade-11ee-a976-f4b520322e15",
    "Терминал_Key": "49b9390d-51f8-11f0-be25-00155d00f705",
    "Выход": "Кируу (Вход)",
    "Момент": 1,
    "Минута": "0",
    "ДатаПересечения": "2026-03-13T21:00:00",
    "Статус": "",
    "ФИО": "Жороева Акылай",
    "Обновил_Key": "00000000-0000-0000-0000-000000000000",
    "Место_Key": "021f4fa9-3377-11ed-91a8-a068f8f3337c",
    "НомерПропуска": ""
}


### Создание явки Выход

POST {{$dotenv API}}/InformationRegister_ЯвкиСотрудников
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Accept: application/json

{
    "Сотрудник_Key": "b882bb25-aade-11ee-a976-f4b520322e15",
    "Терминал_Key": "49b9390d-51f8-11f0-be25-00155d00f705",
    "Выход": "Чыгуу (Выход)",
    "Момент": 0,
    "Минута": "1",
    "ДатаПересечения": "2026-03-13T23:01:00",
    "Статус": "",
    "ФИО": "Жороева Акылай",
    "Обновил_Key": "00000000-0000-0000-0000-000000000000",
    "Место_Key": "021f4fa9-3377-11ed-91a8-a068f8f3337c",
    "НомерПропуска": ""
}


